language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-skipcode' ]; then cd .. && eval "mv $currentfolder generator-skipcode" && cd generator-skipcode; fi

